[platformio]
default_envs = lilygo_t3_s3_sx1276

[env:lilygo_t3_s3_sx1276]
platform = espressif32@6.12.0
board = lilygo-t3-s3
framework = arduino
monitor_speed = 115200
upload_speed = 460800
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
build_flags =
  -DCORE_DEBUG_LEVEL=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -ffile-prefix-map=${sysenv.HOME}=/build
  -fmacro-prefix-map=${sysenv.HOME}=/build
  -fdebug-prefix-map=${sysenv.HOME}=/build
lib_deps =
  jgromes/RadioLib@7.7.1
  thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays@4.6.1
